### ISSUE TITLE
赤裸裸地用别人的idea也能发ISPRS？

### ISSUE THREAD

**Issue by epoch8260** [lironui/ABCNet#3]
Ref: 1) . BiseNet_v1
       2).   Real-time Semantic Segmentation with Fast Attention

**Comment by epoch8260** [comment]
更可怕的是 作者里的其中一篇文章还是我审的......

**Comment by lironui** [comment]
感谢提问！我很好奇您是否完整的看过我们的上述文章。
1. 我们文章明确说明**Following the design philosophy of BiSeNet (Yu et al., 2018)**, we design the ABCNet...如果照您的观点，是否BiSeNet之后所有基于bilateral architecture的结构文章都是“赤裸裸地用别人的idea”呢？
2. 关于第二篇文章，如果你仔细阅读过我们的linear attention的文章([Multistage attention ResU-Net for semantic segmentation of fine-resolution remote sensing images]https://ieeexplore.ieee.org/abstract/document/9378788/))，就会发现这是两篇出发点完全不同的文章。您指出的文章是为了避免unbounded values所以用了l2规范化。而我们的idea是首先把点乘使用泰勒展开近似，在近似的过程中为了保证数值为正引入了l2规范化。所以照您的观点，是不是只要使用了l2规范化就是“赤裸裸地用别人的idea”呢？
3. 您所说的文章2，提交arXiv的时间是2020-07-07，而我们linear attention文章的idea是基于博客：https://spaces.ac.cn/archives/7546，而上述博客的发布时间是2020-07-04。所以考虑到这个时间的先后关系，我们也很难“赤裸裸地用别人的idea”吧。
